# Generated by Django 3.0.3 on 2020-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('slug', models.SlugField(default='', unique=True)),
                ('thumbnail', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('slug', models.SlugField(default='', unique=True)),
                ('content', models.TextField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='')),
                ('category', models.ManyToManyField(to='merlo.Category')),
            ],
        ),
    ]
