# Generated by Django 3.0.3 on 2020-02-11 21:58

import backend.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlo', '0002_auto_20200209_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=backend.utils.models.JSONField(blank=True, default='', null=True),
        ),
    ]
