# Generated by Django 3.0.3 on 2020-02-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlo', '0004_auto_20200211_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gitlab',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
