# Generated by Django 3.0.3 on 2020-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlo', '0006_auto_20200211_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
