# Generated by Django 3.0.3 on 2020-02-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlo', '0008_auto_20200213_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=1000, unique=True),
        ),
    ]
